### ISSUE TITLE
Указание релиза платформы для разбора файлов на исходники.

### ISSUE THREAD

**Issue by AnatoliyBritko** [bia-tech/precommit4onec#4]
Необходимо где-то в настройках указать каким релизом платформы разбирать файлы. 
Как я понимаю разбор идет последним установленным релизом (у меня 8.3.12), хотя фактически работа на 8.3.11.
Из за этого не получается собрать назад файл обработки из исходников (различие в версиях).
![image](https://user-images.githubusercontent.com/18395787/43818799-f78ad6d4-9ae8-11e8-8bc9-bc2b461810f0.png)

Подскажите как это лучше сделать?

**Comment by AnatoliyBritko** [comment]
Получается что здесь надо 
https://github.com/bia-tech/precommit4onec/blob/master/src/%D0%A1%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8/%D0%A0%D0%B0%D0%B7%D0%B1%D0%BE%D1%80%D0%9E%D1%82%D1%87%D0%B5%D1%82%D0%BE%D0%B2%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BE%D0%BA%D0%A0%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D0%B9.os#L229-L230
надо прописать 

> Конфигуратор.ИспользоватьВерсиюПлатформы("8.3.11");

Как лучше номер версии сюда пробросить что бы в precommit4onec можно было универсально использовать на разных платформах?

**Comment by theshadowco** [comment]
Сделаю  вближайшем релизе использование конфигов для сценариев. Пока - можно закостылить версию в сценарии
