### ISSUE TITLE
Ошибка при загрузке локальных сценариев

### ISSUE THREAD

**Issue by ProgED** [bia-tech/precommit4onec#6]
precommit4onec\src\Классы\КомандаПрекоммит.os / Ошибка в строке: 220 / Нет доступных сценариев обработки файлов

В 216 строке этого класса вызывается процедура "ЗагрузитьСценарииИзКаталога" без третьего парметра "ИменаЗагружаемыхСценариев", а внутри процедуры всегда идет поиск имен по этому массиву.

**Comment by theshadowco** [comment]
закрыто https://github.com/bia-technologies/precommit4onec/releases/tag/1.10
